source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'omniauth-google-oauth2'
gem 'omniauth-github'
gem 'pg', '~> 0.15'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'

gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'active_model_serializers'
gem 'dotenv-rails'
gem 'activeadmin', '~> 1.0.0.pre2'
gem 'bootstrap', '~> 4.0.0.alpha3'
gem 'font-awesome-rails'
gem 'material_icons'
gem 'materialize-sass'
gem 'bcrypt'
gem 'nokogiri'

gem 'rails-api', require: 'rails-api/action_controller/api'
gem 'ace-rails-ap'
source 'https://rails-assets.org' do
  gem 'rails-assets-tether', '>= 1.1.0'
end

group :development, :test do
  gem "pry-byebug"
  gem 'pry-doc'
  gem 'pry-rails'
  gem 'rspec-rails'
end

group :development do
  gem 'web-console', '~> 2.0'
  gem 'seed_dump'
  gem 'spring'
end

